logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'INFO'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    region: default
    registryFetchIntervalSeconds: 1
    availabilityZones: 
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
